-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 19:11:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abbybot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `abbybot` ;

-- -----------------------------------------------------
-- Schema abbybot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abbybot` ;
USE `abbybot` ;

-- -----------------------------------------------------
-- Table `abbybot`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`languages` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language_code` VARCHAR(5) NOT NULL,
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'in this table, language list will be saved, in this case only \'en\' English and \'sp\' Spanish.';


-- -----------------------------------------------------
-- Table `abbybot`.`server_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`server_settings` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`server_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guild_id` BIGINT NOT NULL,
  `guild_name` VARCHAR(100) NOT NULL,
  `owner_id` BIGINT NOT NULL,
  `member_count` INT NOT NULL,
  `prefix` VARCHAR(45) NOT NULL,
  `activated_events` TINYINT NOT NULL DEFAULT 1,
  `activated_logs` TINYINT NOT NULL DEFAULT 1,
  `logs_channel` BIGINT NULL DEFAULT NULL,
  `guild_language` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guild_language_idx` (`guild_language` ASC) VISIBLE,
  UNIQUE INDEX `guild_id_UNIQUE` (`guild_id` ASC) VISIBLE,
  CONSTRAINT `fk_guild_language`
    FOREIGN KEY (`guild_language`)
    REFERENCES `abbybot`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In this table all servers that uses AbbyBot will be registered.';


-- -----------------------------------------------------
-- Table `abbybot`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`categories` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'In this table the categories for the messages that the \'dialogues\' table will have will be stored.';


-- -----------------------------------------------------
-- Table `abbybot`.`dialogues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`dialogues` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`dialogues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dialogues_1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_languages`
    FOREIGN KEY (`language_id`)
    REFERENCES `abbybot`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `abbybot`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In dialogues table, all quotes that AbbyBot says are saved, in all languages. ';


-- -----------------------------------------------------
-- Table `abbybot`.`help`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`help` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`help` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `command_code` VARCHAR(45) NOT NULL,
  `command_description` VARCHAR(255) NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_language_id_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `abbybot`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In this table all help commands will be registered, in this moment manually.';


-- -----------------------------------------------------
-- Table `abbybot`.`type_event_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`type_event_message` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`type_event_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'in this table are saved the types for event_message table';


-- -----------------------------------------------------
-- Table `abbybot`.`event_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`event_message` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`event_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_language_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `abbybot`.`type_event_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `abbybot`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In this table event messages like mentions or deleted messages are registered.  ';


-- -----------------------------------------------------
-- Table `abbybot`.`mention_counter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`mention_counter` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`mention_counter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `user_server` BIGINT NOT NULL,
  `mention_count` INT NOT NULL DEFAULT 0,
  `last_mention` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index2` (`user_id` ASC, `user_server` ASC) VISIBLE,
  CONSTRAINT `fk_user_server`
    FOREIGN KEY (`user_server`)
    REFERENCES `abbybot`.`server_settings` (`guild_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `abbybot`.`dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abbybot`.`dashboard` ;

CREATE TABLE IF NOT EXISTS `abbybot`.`dashboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guild_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `user_nickname` VARCHAR(45) NOT NULL,
  `date_joined` TIMESTAMP NULL DEFAULT NULL,
  `user_birthday` DATE NULL DEFAULT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_guild_userid_idx` (`guild_id` ASC) VISIBLE,
  CONSTRAINT `fk_guild_userid`
    FOREIGN KEY (`guild_id`)
    REFERENCES `abbybot`.`server_settings` (`guild_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In this table all user dashboard in a server will be saved';

INSERT INTO abbybot.languages (id, language_code, language_name)
VALUES
(1, 'en', 'English'),
(2, 'es', 'Español');


INSERT INTO categories 
VALUES
(1,'About Her'),
(2,'Lore'),
(3,'Advice');



INSERT INTO abbybot.type_event_message (type_message)
VALUES
('normal'),
('angry'),
('forgive');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
